name: base
channels:
  - defaults
dependencies:
  - pip
  - python=3.7
  - pytorch
  - pip:
    - adal
    - nltk
    - requests
    - tokenizers==0.8.1.rc2
    - transformers==3.1.0
    - azureml-defaults
